### ISSUE TITLE
[Bug] Files overwritten with non-functional zero-byte files if download(s) fail

### ISSUE THREAD

**Issue by moldimolt** [ITotalJustice/atmosphere-updater#2]
On clicking "Update the app" without internet, `/switch/atmosphere-updater/atmosphere-updater.nro` was overwritten with a zero-byte file and ceased to function.

**Comment by ITotalJustice** [comment]
Thank you for reporting! I’ll fix this tomorrow 😄

**Comment by moldimolt** [comment]
No problem, thanks!
