### ISSUE TITLE
Add build instructions

### ISSUE THREAD

**Issue by mrhappyasthma** [ITotalJustice/atmosphere-updater#8]
I'm trying to get this makefile running on Windows, and I'm having issues. I think I have most of the dependencies set up now, but it would be helpful if the README included build instructions.

**Comment by ITotalJustice** [comment]
Make sure you have the following installed:

switch-curl
switch-freetype
switch-sdl2
switch-sdl2_gfx
switch-sdl2_image
switch-sdl2_ttf
switch-zlib

**Comment by ITotalJustice** [comment]
If it still fails, please post the post the build log. (Also report back if it works so that i know what to add to the build instructions!).

**Comment by mrhappyasthma** [comment]
Could you clarify how to install those?

I installed the `devkitPro` for Windows. And I manually installed `SDL2`, `SDL2_Image` and `SDL2_ttf` for windows.

Using `cygwin64` I am linking against `curl` and `zlib`.

The error I'm seeing is:

```
aarch64-none-elf-g++.exe: error: unrecognized command line option '-mwindows'
```

**Comment by mrhappyasthma** [comment]
I'm able to install those specific packages on Mac. Still not sure how to install them on Windows.

**Comment by mrhappyasthma** [comment]
Okay, turns out the install instructions don't explain that you need to use `pacman -S <lib>` command line tool to install those deps on Windows.

After installing all of those deps, I'm getting this error:

```
linking atmosphere-updater.elf
d:/devkitpro/devkita64/bin/../lib/gcc/aarch64-none-elf/8.3.0/../../../../aarch64-none-elf/bin/ld.exe: D:/devkitPro/libnx/lib\libnx.a(switch_crt0.o): in function `bss_loop':
/home/fincs/pacman-packages/libnx/src/libnx-2.5.0/nx/source/runtime/switch_crt0.s:72: undefined reference to `main'
collect2.exe: error: ld returned 1 exit status
make[1]: *** [/opt/devkitpro/libnx/switch_rules:80: /d/GitHub/atmosphere-updater/atmosphere-updater.elf] Error 1
make: *** [Makefile:170: build] Error 2
```

**Comment by mrhappyasthma** [comment]
Ah, success! I needed to `make clean` first. Some of the build products must have been stale.

**Comment by ITotalJustice** [comment]
Sorry, I should've specified that you needed to use the dkp toolchain (which you did in the end).

I'm glad you managed to compile in the end, also thank you for reporting back. I'll add build instructions either later today or tomorrow (going to re-open this issue until then).
